### ISSUE TITLE
Error while building from Docker file

### ISSUE THREAD

**Issue by masterbpro** [blakev/pasta#1]
I tried to build and run, but I get this error:

`$ sudo docker build --tag paste-service .
Sending build context to Docker daemon  121.3kB
Step 1/12 : FROM python:3-alpine
3-alpine: Pulling from library/python
188c0c94c7c5: Pull complete 
55578f60cda7: Pull complete 
692da2fcb614: Pull complete 
599e2857d4f0: Pull complete 
8c3f3cede5b3: Pull complete 
Digest: sha256:bd2606d18cbc21f9c7f7ca924bb1aa46ab4c5c9997299caea7760bfbe59b6fa4
Status: Downloaded newer image for python:3-alpine
 ---> 77a605933afb
Step 2/12 : MAINTAINER "Blake VandeMerwe <blakev@null.net>"
 ---> Running in ef8c8ac35489
Removing intermediate container ef8c8ac35489
 ---> 57f475b7eb38
Step 3/12 : EXPOSE 8000
 ---> Running in 24f51115dc3b
Removing intermediate container 24f51115dc3b
 ---> d823dc0c6eeb
Step 4/12 : RUN mkdir -p     /var/log/pasta     /data     /app
 ---> Running in c18444b3f09c
Removing intermediate container c18444b3f09c
 ---> 9de91bf8a9d4
Step 5/12 : WORKDIR /app
 ---> Running in efaab2f87ab4
Removing intermediate container efaab2f87ab4
 ---> f261c5c9aa50
Step 6/12 : RUN apk add --update     build-base     libffi-dev     openssl-dev
 ---> Running in 96ec758fb396
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/community/x86_64/APKINDEX.tar.gz
(1/24) Installing libgcc (9.3.0-r2)
(2/24) Installing libstdc++ (9.3.0-r2)
(3/24) Installing binutils (2.34-r1)
(4/24) Installing libmagic (5.38-r0)
(5/24) Installing file (5.38-r0)
(6/24) Installing gmp (6.2.0-r0)
(7/24) Installing isl (0.18-r0)
(8/24) Installing libgomp (9.3.0-r2)
(9/24) Installing libatomic (9.3.0-r2)
(10/24) Installing libgphobos (9.3.0-r2)
(11/24) Installing mpfr4 (4.0.2-r4)
(12/24) Installing mpc1 (1.1.0-r1)
(13/24) Installing gcc (9.3.0-r2)
(14/24) Installing musl-dev (1.1.24-r9)
(15/24) Installing libc-dev (0.7.2-r3)
(16/24) Installing g++ (9.3.0-r2)
(17/24) Installing make (4.3-r0)
(18/24) Installing fortify-headers (1.1-r0)
(19/24) Installing patch (2.7.6-r6)
(20/24) Installing build-base (0.5-r2)
(21/24) Installing linux-headers (5.4.5-r1)
(22/24) Installing pkgconf (1.7.2-r0)
(23/24) Installing libffi-dev (3.3-r2)
(24/24) Installing openssl-dev (1.1.1g-r0)
Executing busybox-1.31.1-r19.trigger
OK: 220 MiB in 59 packages
Removing intermediate container 96ec758fb396
 ---> 1b257ab29912
Step 7/12 : COPY ./requirements.txt /app
 ---> 88ba761d3d92
Step 8/12 : RUN python -m pip install --no-cache-dir -r requirements.txt
 ---> Running in 26bbae8ba83f
Collecting asn1crypto==0.24.0
  Downloading asn1crypto-0.24.0-py2.py3-none-any.whl (101 kB)
Collecting cffi==1.12.2
  Downloading cffi-1.12.2.tar.gz (453 kB)
Collecting Click==7.0
  Downloading Click-7.0-py2.py3-none-any.whl (81 kB)
Collecting cryptography==2.6.1
  Downloading cryptography-2.6.1.tar.gz (491 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
    Preparing wheel metadata: started
    Preparing wheel metadata: finished with status 'done'
Collecting easydict==1.9
  Downloading easydict-1.9.tar.gz (6.4 kB)
Collecting Flask==1.0.2
  Downloading Flask-1.0.2-py2.py3-none-any.whl (91 kB)
Collecting Flask-WTF==0.14.2
  Downloading Flask_WTF-0.14.2-py2.py3-none-any.whl (14 kB)
Collecting gunicorn==19.9.0
  Downloading gunicorn-19.9.0-py2.py3-none-any.whl (112 kB)
Collecting itsdangerous==1.1.0
  Downloading itsdangerous-1.1.0-py2.py3-none-any.whl (16 kB)
Collecting Jinja2==2.10
  Downloading Jinja2-2.10-py2.py3-none-any.whl (126 kB)
Collecting MarkupSafe==1.1.1
  Downloading MarkupSafe-1.1.1.tar.gz (19 kB)
Collecting pycparser==2.19
  Downloading pycparser-2.19.tar.gz (158 kB)
Collecting six==1.12.0
  Downloading six-1.12.0-py2.py3-none-any.whl (10 kB)
Collecting toml==0.10.0
  Downloading toml-0.10.0-py2.py3-none-any.whl (25 kB)
Collecting toolz==0.9.0
  Downloading toolz-0.9.0.tar.gz (45 kB)
Collecting Werkzeug==0.14.1
  Downloading Werkzeug-0.14.1-py2.py3-none-any.whl (322 kB)
Collecting WTForms==2.2.1
  Downloading WTForms-2.2.1-py2.py3-none-any.whl (166 kB)
Building wheels for collected packages: cffi, cryptography, easydict, MarkupSafe, pycparser, toolz
  Building wheel for cffi (setup.py): started
  Building wheel for cffi (setup.py): finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: /usr/local/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-la81ykk4/cffi/setup.py'"'"'; __file__='"'"'/tmp/pip-install-la81ykk4/cffi/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-5q3xxgck
       cwd: /tmp/pip-install-la81ykk4/cffi/
  Complete output (55 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.9
  creating build/lib.linux-x86_64-3.9/cffi
  copying cffi/commontypes.py -> build/lib.linux-x86_64-3.9/cffi
  copying cffi/model.py -> build/lib.linux-x86_64-3.9/cffi
  copying cffi/vengine_cpy.py -> build/lib.linux-x86_64-3.9/cffi
  copying cffi/pkgconfig.py -> build/lib.linux-x86_64-3.9/cffi
  copying cffi/backend_ctypes.py -> build/lib.linux-x86_64-3.9/cffi
  copying cffi/verifier.py -> build/lib.linux-x86_64-3.9/cffi
  copying cffi/vengine_gen.py -> build/lib.linux-x86_64-3.9/cffi
  copying cffi/__init__.py -> build/lib.linux-x86_64-3.9/cffi
  copying cffi/api.py -> build/lib.linux-x86_64-3.9/cffi
  copying cffi/recompiler.py -> build/lib.linux-x86_64-3.9/cffi
  copying cffi/cparser.py -> build/lib.linux-x86_64-3.9/cffi
  copying cffi/cffi_opcode.py -> build/lib.linux-x86_64-3.9/cffi
  copying cffi/error.py -> build/lib.linux-x86_64-3.9/cffi
  copying cffi/lock.py -> build/lib.linux-x86_64-3.9/cffi
  copying cffi/ffiplatform.py -> build/lib.linux-x86_64-3.9/cffi
  copying cffi/setuptools_ext.py -> build/lib.linux-x86_64-3.9/cffi
  copying cffi/_cffi_include.h -> build/lib.linux-x86_64-3.9/cffi
  copying cffi/parse_c_type.h -> build/lib.linux-x86_64-3.9/cffi
  copying cffi/_embedding.h -> build/lib.linux-x86_64-3.9/cffi
  copying cffi/_cffi_errors.h -> build/lib.linux-x86_64-3.9/cffi
  running build_ext
  building '_cffi_backend' extension
  creating build/temp.linux-x86_64-3.9
  creating build/temp.linux-x86_64-3.9/c
  gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -DTHREAD_STACK_SIZE=0x100000 -fPIC -DUSE__THREAD -DHAVE_SYNC_SYNCHRONIZE -I/usr/local/include/python3.9 -c c/_cffi_backend.c -o build/temp.linux-x86_64-3.9/c/_cffi_backend.o
  c/_cffi_backend.c: In function 'prepare_callback_info_tuple':
  c/_cffi_backend.c:5987:5: warning: 'PyEval_InitThreads' is deprecated [-Wdeprecated-declarations]
   5987 |     PyEval_InitThreads();
        |     ^~~~~~~~~~~~~~~~~~
  In file included from /usr/local/include/python3.9/Python.h:145,
                   from c/_cffi_backend.c:2:
  /usr/local/include/python3.9/ceval.h:130:37: note: declared here
    130 | Py_DEPRECATED(3.9) PyAPI_FUNC(void) PyEval_InitThreads(void);
        |                                     ^~~~~~~~~~~~~~~~~~
  c/_cffi_backend.c: In function 'b_callback':
  c/_cffi_backend.c:6042:5: warning: 'ffi_prep_closure' is deprecated: use ffi_prep_closure_loc instead [-Wdeprecated-declarations]
   6042 |     if (ffi_prep_closure(closure, &cif_descr->cif,
        |     ^~
  In file included from c/_cffi_backend.c:15:
  /usr/include/ffi.h:334:1: note: declared here
    334 | ffi_prep_closure (ffi_closure*,
        | ^~~~~~~~~~~~~~~~
  In file included from c/cffi1_module.c:20,
                   from c/_cffi_backend.c:7552:
  c/call_python.c: In function '_get_interpstate_dict':
  c/call_python.c:26:30: error: dereferencing pointer to incomplete type 'PyInterpreterState' {aka 'struct _is'}
     26 |     builtins = tstate->interp->builtins;
        |                              ^~
  error: command '/usr/bin/gcc' failed with exit code 1
  ----------------------------------------
  ERROR: Failed building wheel for cffi
  Running setup.py clean for cffi
  Building wheel for cryptography (PEP 517): started
  Building wheel for cryptography (PEP 517): still running...
  Building wheel for cryptography (PEP 517): finished with status 'done'
  Created wheel for cryptography: filename=cryptography-2.6.1-cp39-cp39-linux_x86_64.whl size=362795 sha256=d9bcdb60a122ac0c3a876ebf8b19da7ff2435a74743907268cf5c3577dbc91df
  Stored in directory: /tmp/pip-ephem-wheel-cache-v1i3n8jz/wheels/ee/a6/4b/d52ce138b0aa5933a518beaee134cc81b5803c502958c45018
  Building wheel for easydict (setup.py): started
  Building wheel for easydict (setup.py): finished with status 'done'
  Created wheel for easydict: filename=easydict-1.9-py3-none-any.whl size=6350 sha256=84034a4fd7c5046a53118d2cb127880a12aed2ad2175c6081591f25fbed1f9bc
  Stored in directory: /tmp/pip-ephem-wheel-cache-v1i3n8jz/wheels/b2/1c/36/fd8efc3fa029b1445d869f359ec13e8fbce7fc9e81505bca66
  Building wheel for MarkupSafe (setup.py): started
  Building wheel for MarkupSafe (setup.py): finished with status 'done'
  Created wheel for MarkupSafe: filename=MarkupSafe-1.1.1-cp39-cp39-linux_x86_64.whl size=17699 sha256=34db725d8a6b168d970740c276eebead009e1db576b021db0720140919b92925
  Stored in directory: /tmp/pip-ephem-wheel-cache-v1i3n8jz/wheels/e0/19/6f/6ba857621f50dc08e084312746ed3ebc14211ba30037d5e44e
  Building wheel for pycparser (setup.py): started
  Building wheel for pycparser (setup.py): finished with status 'done'
  Created wheel for pycparser: filename=pycparser-2.19-py2.py3-none-any.whl size=111031 sha256=ac41f60b25f5dd21148e115ef3050c0445266a26f6c8bc61ccd6293475f95688
  Stored in directory: /tmp/pip-ephem-wheel-cache-v1i3n8jz/wheels/4c/33/cc/4f98d7defeaadac79c493a4343d33e2317f68f52b33115569b
  Building wheel for toolz (setup.py): started
  Building wheel for toolz (setup.py): finished with status 'done'
  Created wheel for toolz: filename=toolz-0.9.0-py3-none-any.whl size=53237 sha256=5206a12e8bab8e000203c20e3d21c1a90333ac23bb9b56be88969e660601733c
  Stored in directory: /tmp/pip-ephem-wheel-cache-v1i3n8jz/wheels/d6/2b/93/cddc73b00b1de344f71b1995ea9de59d3ab69336cab53cdb9a
Successfully built cryptography easydict MarkupSafe pycparser toolz
Failed to build cffi
Installing collected packages: asn1crypto, pycparser, cffi, Click, six, cryptography, easydict, Werkzeug, itsdangerous, MarkupSafe, Jinja2, Flask, WTForms, Flask-WTF, gunicorn, toml, toolz
    Running setup.py install for cffi: started
    Running setup.py install for cffi: finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-la81ykk4/cffi/setup.py'"'"'; __file__='"'"'/tmp/pip-install-la81ykk4/cffi/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-_py9c3wz/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.9/cffi
         cwd: /tmp/pip-install-la81ykk4/cffi/
    Complete output (55 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.9
    creating build/lib.linux-x86_64-3.9/cffi
    copying cffi/commontypes.py -> build/lib.linux-x86_64-3.9/cffi
    copying cffi/model.py -> build/lib.linux-x86_64-3.9/cffi
    copying cffi/vengine_cpy.py -> build/lib.linux-x86_64-3.9/cffi
    copying cffi/pkgconfig.py -> build/lib.linux-x86_64-3.9/cffi
    copying cffi/backend_ctypes.py -> build/lib.linux-x86_64-3.9/cffi
    copying cffi/verifier.py -> build/lib.linux-x86_64-3.9/cffi
    copying cffi/vengine_gen.py -> build/lib.linux-x86_64-3.9/cffi
    copying cffi/__init__.py -> build/lib.linux-x86_64-3.9/cffi
    copying cffi/api.py -> build/lib.linux-x86_64-3.9/cffi
    copying cffi/recompiler.py -> build/lib.linux-x86_64-3.9/cffi
    copying cffi/cparser.py -> build/lib.linux-x86_64-3.9/cffi
    copying cffi/cffi_opcode.py -> build/lib.linux-x86_64-3.9/cffi
    copying cffi/error.py -> build/lib.linux-x86_64-3.9/cffi
    copying cffi/lock.py -> build/lib.linux-x86_64-3.9/cffi
    copying cffi/ffiplatform.py -> build/lib.linux-x86_64-3.9/cffi
    copying cffi/setuptools_ext.py -> build/lib.linux-x86_64-3.9/cffi
    copying cffi/_cffi_include.h -> build/lib.linux-x86_64-3.9/cffi
    copying cffi/parse_c_type.h -> build/lib.linux-x86_64-3.9/cffi
    copying cffi/_embedding.h -> build/lib.linux-x86_64-3.9/cffi
    copying cffi/_cffi_errors.h -> build/lib.linux-x86_64-3.9/cffi
    running build_ext
    building '_cffi_backend' extension
    creating build/temp.linux-x86_64-3.9
    creating build/temp.linux-x86_64-3.9/c
    gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -DTHREAD_STACK_SIZE=0x100000 -fPIC -DUSE__THREAD -DHAVE_SYNC_SYNCHRONIZE -I/usr/local/include/python3.9 -c c/_cffi_backend.c -o build/temp.linux-x86_64-3.9/c/_cffi_backend.o
    c/_cffi_backend.c: In function 'prepare_callback_info_tuple':
    c/_cffi_backend.c:5987:5: warning: 'PyEval_InitThreads' is deprecated [-Wdeprecated-declarations]
     5987 |     PyEval_InitThreads();
          |     ^~~~~~~~~~~~~~~~~~
    In file included from /usr/local/include/python3.9/Python.h:145,
                     from c/_cffi_backend.c:2:
    /usr/local/include/python3.9/ceval.h:130:37: note: declared here
      130 | Py_DEPRECATED(3.9) PyAPI_FUNC(void) PyEval_InitThreads(void);
          |                                     ^~~~~~~~~~~~~~~~~~
    c/_cffi_backend.c: In function 'b_callback':
    c/_cffi_backend.c:6042:5: warning: 'ffi_prep_closure' is deprecated: use ffi_prep_closure_loc instead [-Wdeprecated-declarations]
     6042 |     if (ffi_prep_closure(closure, &cif_descr->cif,
          |     ^~
    In file included from c/_cffi_backend.c:15:
    /usr/include/ffi.h:334:1: note: declared here
      334 | ffi_prep_closure (ffi_closure*,
          | ^~~~~~~~~~~~~~~~
    In file included from c/cffi1_module.c:20,
                     from c/_cffi_backend.c:7552:
    c/call_python.c: In function '_get_interpstate_dict':
    c/call_python.c:26:30: error: dereferencing pointer to incomplete type 'PyInterpreterState' {aka 'struct _is'}
       26 |     builtins = tstate->interp->builtins;
          |                              ^~
    error: command '/usr/bin/gcc' failed with exit code 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/local/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-la81ykk4/cffi/setup.py'"'"'; __file__='"'"'/tmp/pip-install-la81ykk4/cffi/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-_py9c3wz/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.9/cffi Check the logs for full command output.
The command '/bin/sh -c python -m pip install --no-cache-dir -r requirements.txt' returned a non-zero code: 1
`

**Comment by blakev** [comment]
I haven't looked at this project for awhile! I'll try and take some time to fix the dockerfile!
